### ISSUE TITLE
Algorand slip10-secp256k1 support

### ISSUE THREAD

**Issue by Fantom579** [ebellocchia/py_crypto_hd_wallet#13]
Please add slip10-secp256k1 Algorand support.

**Comment by ebellocchia** [comment]
Hi,
ok it's pretty straightforward to add, can you suggest a wallet that I can use to verify the addresses?

Thanks

**Comment by Fantom579** [comment]
Hello, use Exodus wallet to verify the Algorand addresses. Here is the source from which I concluded that Exodus uses this elliptical curve: https://algorand.oortnet.com/
I also noticed that addresses are generated in a special way in the Exodus wallet: Solana, Cardano, Stellar, and I assume that these particular coins also use the slip10-secp256k1 elliptic curve. However, I do not have enough keyboard keys to test this, and I have not found any tools that can prove it.

Thank you for your work.

**Comment by ebellocchia** [comment]
Oh yes, I know how Exodus works because another user has already asked me for the bip_utils library.
Basically, it derives a standard BIP44 path using the secp256k1 curve and then it uses the last derived private key as a ed25519 key (because those coins need the ed25519 in any case).
I posted a working code in this issue (it was for Solana, but you just need to change the coin index):

https://github.com/ebellocchia/bip_utils/issues/38#issuecomment-959825538
