### ISSUE TITLE
How to derive a private key? 

### ISSUE THREAD

**Issue by stdusr** [ebellocchia/py_crypto_hd_wallet#2]

**Comment by ebellocchia** [comment]
Hello,
the private key is only one and it is correct, otherwise all addresses and public keys will be wrong. The bytes of the private key are in the _raw_priv_ key of the dictionary. However, to make the key easier to read various formats are used, but they always refer to the same private key. Usually, wallets support [WIF encoding](https://en.bitcoin.it/wiki/Wallet_import_format), which is _wif_priv_ in the dict, or the extended format, which is _ex_priv_ in the dict.
As far as I know, for Bitcoin, the WIF encoding always starts with 5 (for main net) or 9 (for test net). However, I noticed now the following sentence in the WIF documentation:
> Drop the first byte (it should be 0x80). If the private key corresponded to a compressed public key, also drop the last byte (it should be 0x01). If it corresponded to a compressed public key, the WIF string will have started with K or L instead of 5 (or c instead of 9 on testnet). This is the private key.

That's the reason why the WIF computed by my library is different from the one in the website (I'm not adding the `0x01` at the end). I can update the bip_utils library for supporting it.

Thanks

**Comment by stdusr** [comment]
Many thanks for a quick response. I read it very attentively, but unfortunately, all the binary stuff is beyond my expertise. Would it require much effort and time for you to update the package to support it? Also, do you accept donations?

**Comment by ebellocchia** [comment]
Yes I definitely can, I just need some days because I have to update also the unit tests.
If you'd like to donate something, I thank you a lot in advance, I appreciate it. You can use:

- Paypal: emanuele.bellocchia@gmail.com
- BTC: bc1qxr3camglhmrcl5uhs2m5hmaxmrxf47krs3fzpm

**Comment by stdusr** [comment]
Sent a bit of BTC, will add more later :)

**Comment by ebellocchia** [comment]
Thank you very much.
I updated both the wallet and the bip_utils library to generate the correct WIF encoding, I also took advantage of this for adding Bitcoin Cash and BitcoinSV to supported coins.

**Comment by stdusr** [comment]
A very big thank you! Before I found your package, I was deriving private keys probably the dumbest way - automating this utility: https://iancoleman.io/bip39/ with Selenium :) And(not to bother you), could you give a hint or direction,  how do I get WIF private key for Ethereum? As I see, it works only for Bitcoin :(

**Comment by ebellocchia** [comment]
You're welcome.
Ethereum doesn't support WIF format, you can simply use the raw bytes of the private key for it (*raw_priv* in the dict, just add 0x in front of it and you'll get the same value of the website).

**Comment by stdusr** [comment]
Thanks again. Not to offence, but I made another small BTC donation. When I will earn more with the help of your library, I am morally obliged to donate more :)
