### ISSUE TITLE
How to generate many addresses from a parent address

### ISSUE THREAD

**Issue by haysquareA** [ebellocchia/py_crypto_hd_wallet#27]
Hello there,
I'm working on a project requiring a parent address with many child addresses that could be used to receive coins.

For example, Address A would be able to create child 1, child 2 and child 3 .....
and those children could be used to receive coins that will go straight to the parent's Address A,
Please what's the best approach to achieve this?
Thanks a lot in advance

**Comment by ebellocchia** [comment]
Hello,
I'm not sure I understood 100% what you want to do.
First of all, you derive keys not addresses, so you need the parent private key (with the derivation data, chain code in particular) to derive its children keys. Also the public key can used, if not hardened derivation is supported, which results in a watch-only wallet, but if you need child addresses to automatically transfer funds to the parent one you need the private key. The problem of doing this is to display the the balance from a wallet (unless you implement it), because wallets usually derive the entire path up to the address index keys and doesn't scan the intermediate ones.
So, in principle, you should derive the parent key from the mnemonic phrase at the desired level (e.g. account), store it somewhere and from there you derive children.

**Comment by haysquareA** [comment]
Thanks a lot for the response, I really appreciate.
I'm doing that at the moment,
Does that mean funds from child addresses are automatically going to the parent  and accessible via parent private key?

**Comment by ebellocchia** [comment]
No, for "automatically" I meant that you should write a bot that scans addresses and transfer funds when a TX is detected
